In [1]:
import numpy as np
import sympy
from sympy.abcc import x

### 请利用sympy模块中的函数/方法求极限

In [5]:
sympy.limit(x * sympy.log(sympy.sqrt(2) + 1/ x), x, sympy.oo)

oo

### 从任一一维数组中取出最小和最大的n个数。

In [6]:
a = np.random.rand(10)
# 找最小和最大的3个数
args = a.argsort()
print(a[args[:3]], a[args[-3:]])

[0.25607982 0.25790785 0.26291512] [0.70552532 0.72157259 0.82091919]


###  从正态分布N(5,5)中采样1000个样本，构建为一维数组。

①   计算数组的最大值、最小值、均值、标准差、三个四分位数并保留3位小数格式化输出；

②   打印数组中的数据类型，并计算数组所占据的内存大小；

③   将数组的数据类型转换为int32后再次计算内存大小。

In [15]:
a = np.random.normal(5, 5, 1000)
print("max={:.3f}, min={:.3f}, mean={:.3f}, std={:.3f}, quartiles=[{:.3f},{:.3f},{:.3f}]".format(
     a.max(), a.min(), a.mean(), a.std(), *np.quantile(a, [.25, .50, .75])))
print("element type={}, memory size={}B".format(a.dtype, a.itemsize * a.size))
a = a.astype(np.int32)
print("memory size={}B".format(a.itemsize*a.size))

max=21.321, min=-11.335, mean=5.150, std=5.006, quartiles=[1.754,5.206,8.718]
element type=float64, memory size=8000B
memory size=4000B


### 从均匀分布U[-10,10)中采样，创建一个5*4的二维数组。

①   将数组中最大的2个与最小的2个数重新赋值为0；(若存在多个最大和最小值任取即可，共修改4个数)；

②   统计数组中绝对值在 (4,6) 之间的数据个数。

In [22]:
a = np.random.uniform(-10, 10, (5,4))
x, y = np.unravel_index(a.argsort(axis=None), a.shape)
a[x[:2], y[:2]], a[x[-2:], y[-2:]] = 0, 0
print(a)

print(np.sum((np.abs(a) > 4) & (np.abs(a) < 6)))

[[-5.48295736  1.23911863  1.06717831  2.97089872]
 [-3.55281591  0.          1.99454777  0.        ]
 [-0.81947626  2.32015765  5.57088381  4.63583369]
 [ 4.30939182  5.00382051  8.89533786  0.        ]
 [-1.83742039 -0.12056472  0.          2.21466479]]
5


###  用numpy模块中的函数读取DJI.csv文件，完成如下任务：

①   计算开盘价的均值；

②   计算收盘价大于27000的天数；

③   计算后一天收盘价大于前一天收盘价的总天数（提示：用np.diff()函数）。

In [29]:
a = np.loadtxt('DJI.csv', skiprows=1, usecols=(1, 4), delimiter=',')

print("开盘价均值:{}".format(np.mean(a[:, 0])))
print("收盘价大于27000的天数:{}".format(np.sum(a[:, 1]>27000)))
print("收一天收盘价大于前一天收盘价的总天数:{}".format(np.sum(np.diff(a[:, 1])>0)))

开盘价均值:25643.077852741037
收盘价大于27000的天数:14
收一天收盘价大于前一天收盘价的总天数:132


### 已知有数据："1, 2.3, 3, 4, 5\n6.7,  ,  , 7, 8.5\n  ,  , 9.0,10,11\n"，利用IO功能将其读取到数组中（先将上述字符串转换为IO流）,保存为整型，缺少的部分使用-99填充，最后按序打印-99的列索引。

In [37]:
from io import StringIO
s = StringIO("1, 2.3, 3, 4, 5\n6.7, , , 7, 8.5\n , , 9.0,10,11\n")

a = np.genfromtxt(s, dtype=np.int, delimiter=',', filling_values=-99)
x, y = np.where(a == -99)
print(y)

[1 2 0 1]


### 定义一个普通的标量函数，其功能为计算数字型字符串参数各位数字和，将此标量函数向量化，并创建一个元素为1~1000的ndarray数组进行测试。

In [41]:
f = lambda s: sum(map(int, s))
uf = np.frompyfunc(f, 1, 1)
a = np.array(list(map(str, np.arange(1, 1001))))
uf(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4,
       5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7,
       8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8,
       9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8,
       9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10,
       11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12,
       13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13,
       14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13,
       14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4,
       5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6,
       7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7,
       8, 9, 10, 11, 12, 13, 14, 15, 16